#pragma once

enum ExceptionType {
	PLAYER_OUT_OF_BUDGET = 10,
	BANK_OUT_OF_FUNDS = 11,
	FILE_READ_LINE_EMPTY = 20,
	FILE_READ_CARD_REGEX_FAIL = 21,
	CARD_INDEX_OUT_OF_BOUND = 30,
	CARD_UNKNOWN_AGE = 31,
	CARD_UNKNOWN_COLOR = 32,
	DECK_NOT_FOUND = 40
};
