#pragma once

enum ExceptionType {
	PLAYER_OUT_OF_BUDGET = 10,
	BANK_OUT_OF_FUNDS = 11,
//
	FILE_NOT_FOUND = 20,
	FILE_READ_LINE_EMPTY = 21,
	FILE_READ_CARD_REGEX_FAIL = 22,
	FILE_READ_WONDER_REGEX_FAIL = 23,
//
	CARD_INDEX_OUT_OF_BOUND = 30,
	CARD_UNKNOWN_AGE = 31,
	CARD_UNKNOWN_COLOR = 32,
	CARD_INVALID_STATE = 33,
	WONDER_INDEX_OUT_OF_BOUND = 34,
//
	DECK_NOT_FOUND = 40,
	DECK_OUT_OF_CARDS = 41,
	DECK_NO_VISIBLE_CARDS = 42,
	NO_WONDERS_TO_SELECT = 43,
//
	DISPLAY_ROW_MISMATCH = 50,
//
	CONSOL_NO_PLAYER_TYPE = 60,
	CONSOL_NO_PLAYER_NAME = 61
};
