#pragma once

enum ExceptionType {
	PLAYER_OUT_OF_BUDGET = 10,
	BANK_OUT_OF_FUNDS = 11,
	FILE_NOT_FOUND = 20,
	FILE_READ_LINE_EMPTY = 21,
	FILE_READ_CARD_REGEX_FAIL = 22,
	CARD_INDEX_OUT_OF_BOUND = 30,
	CARD_UNKNOWN_AGE = 31,
	CARD_UNKNOWN_COLOR = 32,
	CARD_INVALID_STATE = 33,
	DECK_NOT_FOUND = 40,
	DECK_TOO_MANY_VISIBLE_CARDS = 41,
	DECK_OUT_OF_CARDS = 42,
	DISPLAY_ROW_MISMATCH = 50
};
